# Generated by Django 5.0.4 on 2024-05-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='gallery/default.jpg', upload_to='gallery'),
        ),
    ]
